#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { existsSync, readdirSync, statSync, readFileSync } from "node:fs";
import { join, relative, resolve, sep } from "node:path";
const ROOT = resolve(process.cwd());
function safePath(input: string): string { const target=resolve(ROOT,input); const rel=relative(ROOT,target); if(rel==='..'||rel.startsWith(`..${sep}`)) throw new Error(`Path is outside the framework workspace: ${input}`); return target; }
function usage(): never { console.log(`\nAgentic QA Tool Layer\n\nCommands:\n  read <path>\n  list <directory>\n  search <directory> <term>\n  run <command>\n  test [playwright args...]\n  git-diff\n`); process.exit(1); }
function listDirectory(directory:string):void { const dir=safePath(directory); if(!existsSync(dir)||!statSync(dir).isDirectory()) throw new Error(`Directory not found: ${directory}`); for(const e of readdirSync(dir,{withFileTypes:true})) console.log(`${e.isDirectory()?'[DIR] ':'[FILE]'} ${e.name}`); }
function searchDirectory(directory:string,term:string):void { const dir=safePath(directory); const ignored=new Set(['node_modules','.git','playwright-report','test-results','dist']); function walk(current:string):void { for(const e of readdirSync(current,{withFileTypes:true})){ if(ignored.has(e.name)) continue; const full=join(current,e.name); if(e.isDirectory()){walk(full);continue;} if(!/\.(ts|tsx|js|jsx|json|md|yaml|yml|css|html)$/.test(e.name)) continue; try{if(readFileSync(full,'utf8').toLowerCase().includes(term.toLowerCase())) console.log(relative(ROOT,full));}catch{} } } walk(dir); }
function runShell(command:string):void { console.log(`\n$ ${command}\n`); const r=spawnSync(command,{cwd:ROOT,shell:true,stdio:'inherit'}); process.exitCode=r.status??1; }
function runPlaywright(args:string[]):void { const project=safePath('target-project'); if(!existsSync(project)) throw new Error('target-project directory does not exist.'); console.log(`\n$ npx playwright test ${args.join(' ')}\n`); const exe=process.platform==='win32'?'npx.cmd':'npx'; const r=spawnSync(exe,['playwright','test',...args],{cwd:project,stdio:'inherit',shell:false}); process.exitCode=r.status??1; }
function gitDiff():void { const exe=process.platform==='win32'?'git.exe':'git'; const r=spawnSync(exe,['diff','--','target-project'],{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']}); if(r.stdout) process.stdout.write(r.stdout); if(r.stderr) process.stderr.write(r.stderr); process.exitCode=r.status??1; }
const [command,...args]=process.argv.slice(2);
try { switch(command){ case 'read': if(!args[0]) usage(); {const f=safePath(args[0]); if(!existsSync(f)||!statSync(f).isFile()) throw new Error(`File not found: ${args[0]}`); process.stdout.write(readFileSync(f,'utf8'));} break; case 'list': if(!args[0]) usage(); listDirectory(args[0]); break; case 'search': if(!args[0]||!args[1]) usage(); searchDirectory(args[0],args[1]); break; case 'run': if(!args.length) usage(); runShell(args.join(' ')); break; case 'test': runPlaywright(args); break; case 'git-diff': gitDiff(); break; default: usage(); } } catch(error){ console.error(`ERROR: ${error instanceof Error?error.message:String(error)}`); process.exit(1); }
